package districoll.cmd;

public enum Cmd {
	// 公共部分
	RSP_OK, RSP_FAIL,
	// 成员管理
	REQ_NODETYPE, RSP_SERVERNODE, RSP_CLIENTNODE,
	// 数据操作
	REQ_PARTITION_REFRESH, REQ_PARTITION_GET, REQ_PARTITION_DEL, REQ_LIST_CLEAR,
	// 元数据管理
	REQ_META_ADD, REQ_META_GET, REQ_META_DEL, REQ_META_NEWPARTITION,
	// 数据计算
	REQ_LIST_FILTER;
}
